services:
  db: # makes DB available. JDBC-URL: "jdbc:postgresql://localhost:15443/"
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: edde_db_local
      POSTGRES_USER: edde # DB user
      POSTGRES_PASSWORD: edde # DB password
    ports:
      - "15433:5432"  # Map local port 15433 to the container's PostgreSQL port 5432