spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:15433/edde_db_local?currentSchema\=edde_dev
    username: edde
    password: edde
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    validateOnMigrate: false

info:
  version: "0.0.0.1"
  name: "0-bee-one [ground studio]"
  deployed: "15.11.2024"
  time: "11:46"

ollama:
  host: http://localhost:11434 #Ollama serve locally on port 11434
  model:
    name: llama3.2

logging:
  level:
    org.flywaydb: INFO
    root: info
server:
  port: 8888
